version: '3'
services:
  charchadb:
    image: postgres:9.6.18
    environment:
      POSTGRES_PASSWORD: charchapassword
  charcha.hashedin.com:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: charcha
    ports:
    - "8000:8000"
    volumes: 
    - "./charcha:/code/charcha"
    environment:
      DATABASE_URL: postgres://postgres:charchapassword@charchadb:5432/postgres
      DJANGO_SETTINGS_MODULE: charcha.settings.common
    depends_on: 
      - charchadb
  charcha.hashedin.com:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: charcha
    volumes: 
    - "./charcha:/code/charcha"
    environment:
      DATABASE_URL: postgres://postgres:charchapassword@charchadb:5432/postgres
      DJANGO_SETTINGS_MODULE: charcha.settings.common
      BASE_URL: http://charcha.hashedin.com:8000/
    depends_on: 
      - charcha.hashedin.com
    command: python manage.py test
